# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-24 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180124_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
