# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-24 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenurl_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url]),
        ),
    ]
